[config]
version_check = false
caching = false
expr_prefix = "{{"
expr_postfix = "}}"
block_prefix = "<*"
block_postfix = "*>"

[config.wallpaper]
# Whether to set the wallpaper or not
set = true
# Command to set the wallpaper using awww
command = "awww"
arguments = ["img", "--transition-type", "center", "--transition-fps", "60"]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hypr-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.wlogout]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty-colors.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship/starship.toml'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'


[templates.zed]
input_path = '~/.config/matugen/templates/zed-colors.json'
output_path = '~/.config/zed/themes/matugen.json'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
