
# #######################################################################################
# HYPRLAND CONFIG.
# EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.
# #######################################################################################


# This is the file hyperland looks into to get configs.
# Actual config files heve been segmented for easy recognition
# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# The configuration has been split as seen below
# Links to the other config files:
#source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/variables.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/env-var.conf
source = ~/.config/hypr/conf/aesthetics.conf
source = ~/.config/hypr/conf/window-rules.conf
#source = ~/.config/hypr/conf/workspaces.conf
source = ~/.config/hypr/conf/permissions.conf
source = ~/.config/hypr/conf/autostart.conf
