#################
## Layer-Rules ##
#################

##    layerrule {
##    name = waybar_rule
##    match:namespace = waybar
##
##    blur = on
##    animation = waybar_anim, 1, 8, default, slidefade 20%
##    ignore_alpha = 0.2
##    }
