###################
###  Variables  ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = alacritty
$fileManager = dolphin
$menu = wofi --show drun
$browser = firefox
$reload_waybar = pkill waybar; waybar
$notes = /home/arch-home/dthkash/Obsidian/Obsidian-1.10.6.AppImage --enable-features=UseOzonePlatform --ozone-platform=wayland
$reload_swaync = swaync-client --reload-config
