##############################
###     WINDOW RULES       ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name= ignore_maximize_request
  match:class = .*

  suppress_event = maximize
}
# Make firefox alittle more opaque
windowrule {
  name = firefox_blur
  match:class = ($browser)

  opacity = 0.95 override 0.55 override
  
}



