# : Manager [[[

[mgr]
cwd = { fg = "#eedfe3" }

# Tab
tab_active = { fg = "#521d3b", bg = "#fdb0d4", bold = true }
tab_inactive = { fg = "#ffd8e8", bg = "#380725" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff9862", bg = "#ff9862" }
marker_cut = { fg = "#ffdbc8", bg = "#ffdbc8" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#f2bb9a", bg = "#f2bb9a" }

# Count
count_copied = { fg = "#301401", bg = "#ffdbc8" }
count_cut = { fg = "#301401", bg = "#ffdbc8" }
count_selected = { fg = "#521d3b", bg = "#f2bb9a" }

# Border
border_symbol = " "
border_style  = { fg = "#fdb0d4" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#521d3b", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#fdb0d4", fg = "#521d3b", bold = true }
normal_alt  = { bg = "#504348", fg = "#d4c2c8" }

# Select mode
select_main = { bg = "#e0bdcb", fg = "#412a34", bold = true }
select_alt  = { bg = "#504348", fg = "#d4c2c8" }

# Unset mode
unset_main = { bg = "#f2bb9a", fg = "#4a2810", bold = true }
unset_alt  = { bg = "#504348", fg = "#d4c2c8" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#fdb0d4", bg = "#40373a" }
progress_error = { fg = "#ffb4ab", bg = "#40373a" }

# Permissions
permissions_t = { fg = "#af5579" }
permissions_w = { fg = "#d7621c" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff772f" }
permissions_s = { fg = "#ff3f8e" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#fdb0d4" }
active = { fg = "#f2bb9a", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#fdb0d4" }
value = { fg = "#eedfe3" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#fdb0d4", bold = true, bg = "#191114" }
inactive = { fg = "#e0bdcb", bg = "#191114" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#fdb0d4", bg = "#521d3b" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#fdb0d4" }
title = {}
hovered = { fg = "#ffdbc8", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#40373a" }
cand = { fg = "#fdb0d4" }
rest = { fg = "#521d3b" }
desc = { fg = "#eedfe3" }
separator = " ▶ "
separator_style = { fg = "#eedfe3" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#eedfe3" }
run = { fg = "#eedfe3" }
footer = { fg = "#412a34", bg = "#e0bdcb" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#f2bb9a" }
title_warn = { fg = "#fdb0d4" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#eedfe3" },
    { name = "*/", fg = "#fdb0d4" },
]

# : ]]]
