# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#eedfe3"

# Title color for boxes
theme[title]="#fdb0d4"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#e0bdcb"

# Background color of selected item in processes box
theme[selected_bg]="#fdb0d4"

# Foreground color of selected item in processes box
theme[selected_fg]="#521d3b"

# Color of inactive/disabled text
theme[inactive_fg]="#d4c2c8"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#f2bb9a"

# Cpu box outline color
theme[cpu_box]="#9d8d92"

# Memory/disks box outline color
theme[mem_box]="#9d8d92"

# Net up/down box outline color
theme[net_box]="#9d8d92"

# Processes box outline color
theme[proc_box]="#9d8d92"

# Box divider line and small boxes line color
theme[div_line]="#504348"

# Temperature graph colors
theme[temp_start]="#e0bdcb"
theme[temp_mid]="#fdb0d4"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#e0bdcb"
theme[cpu_mid]="#fdb0d4"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#e0bdcb"
theme[free_mid]=""
theme[free_end]="#59404b"

# Mem/Disk cached meter
theme[cached_start]="#f2bb9a"
theme[cached_mid]=""
theme[cached_end]="#643e24"

# Mem/Disk available meter
theme[available_start]="#fdb0d4"
theme[available_mid]=""
theme[available_end]="#6d3352"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#e0bdcb"
theme[download_mid]="#fdb0d4"
theme[download_end]="#f2bb9a"

# Upload graph colors
theme[upload_start]="#e0bdcb"
theme[upload_mid]="#fdb0d4"
theme[upload_end]="#f2bb9a"
